# -*- coding: utf-8 -*-
"""CSC412-PreProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J3_AznLk8sBFaLqxf3zxlnWyJWpPO_oI
"""

from google.colab import drive
import requests
import numpy as np
import cv2 
import matplotlib.pyplot as plt
import os

drive_name = '/content/drive'
drive.mount(drive_name)

drive_location = drive_name + '/My Drive/University of Toronto/4th Year/CSC412'
data_location = drive_location + '/data/'

def download_img(object_name):
    """
    Download .npy file for given object_name.
    object_name (str) : Name of object drawing to be downoalded. 
                        E.g., "airplane", "mouse"
    """
    url = "https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/{}.npy".format(object_name)
    myfile = requests.get(url)
    savename = data_location + '{}.npy'.format(object_name)

    if os.path.exists(data_location + '{}.npy'.format(object_name)):
        print("{}.npy file exists already".format(object_name))
    else:
        with open(savename, 'wb') as f:
            f.write(myfile.content)
            print("{}.npy file download completed".format(object_name))
            f.close()


def load_data(object_name):
    """
    Return Nx784 numpy array corresponding to N drawings of size 28x28.
    object_name (str) : Name of object drawing to be loaded to the memory. 
                        E.g., "airplane", "mouse"
    """
    savename = data_location + '{}.npy'.format(object_name)
    data = np.load(savename)

    return data


def display_img(im_arr):
    """
    Plot im_arr.
    im_arr (numpy uint8 array): Numpy array of size (784,) to be visualized.
    """
    plt.imshow(im_arr.reshape(28,28), cmap='gray')

download_img('mouse')

data = load_data('airplane')

display_img(data[1])